/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  InvoiceItem, // @ts-ignore
  Invoice, // @ts-ignore
  Product,
} from "@prisma/client";

export class InvoiceItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.InvoiceItemCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemCountArgs>
  ): Promise<number> {
    return this.prisma.invoiceItem.count(args);
  }

  async invoiceItems<T extends Prisma.InvoiceItemFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemFindManyArgs>
  ): Promise<InvoiceItem[]> {
    return this.prisma.invoiceItem.findMany(args);
  }
  async invoiceItem<T extends Prisma.InvoiceItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemFindUniqueArgs>
  ): Promise<InvoiceItem | null> {
    return this.prisma.invoiceItem.findUnique(args);
  }
  async createInvoiceItem<T extends Prisma.InvoiceItemCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemCreateArgs>
  ): Promise<InvoiceItem> {
    return this.prisma.invoiceItem.create<T>(args);
  }
  async updateInvoiceItem<T extends Prisma.InvoiceItemUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemUpdateArgs>
  ): Promise<InvoiceItem> {
    return this.prisma.invoiceItem.update<T>(args);
  }
  async deleteInvoiceItem<T extends Prisma.InvoiceItemDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.InvoiceItemDeleteArgs>
  ): Promise<InvoiceItem> {
    return this.prisma.invoiceItem.delete(args);
  }

  async getInvoiceId(parentId: string): Promise<Invoice | null> {
    return this.prisma.invoiceItem
      .findUnique({
        where: { id: parentId },
      })
      .invoiceId();
  }

  async getProductId(parentId: string): Promise<Product | null> {
    return this.prisma.invoiceItem
      .findUnique({
        where: { id: parentId },
      })
      .productId();
  }
}
